src/Entity/Job.php
<?php

namespace App\Entity;

use App\Repository\JobRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: JobRepository::class)]
class Job
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;



    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $small_description = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $full_description = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\Column]
    private ?bool $is_published = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\ManyToOne(inversedBy: 'jobs')]
    private ?JobCategory $category = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }



    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getSmallDescription(): ?string
    {
        return $this->small_description;
    }

    public function setSmallDescription(string $small_description): static
    {
        $this->small_description = $small_description;

        return $this;
    }

    public function getFullDescription(): ?string
    {
        return $this->full_description;
    }

    public function setFullDescription(string $full_description): static
    {
        $this->full_description = $full_description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getIsPublished(): ?bool
    {
        return $this->is_published;
    }

    public function setIsPublished(bool $is_published): static
    {
        $this->is_published = $is_published;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getCategory(): ?JobCategory
    {
        return $this->category;
    }

    public function setCategory(?JobCategory $category): static
    {
        $this->category = $category;

        return $this;
    }
}

src/Controller/JobController.php
<?php

namespace App\Controller;

use App\Entity\Job;
use App\Repository\JobCategoryRepository;
use App\Repository\JobRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class JobController extends AbstractController
{
    #[Route('/jobs', name: 'jobs')]
    public function job(JobRepository $jobRepository, JobCategoryRepository $jobCategoryRepository): Response
    {
        $jobs = $jobRepository->findAll();
        $categories = $jobCategoryRepository->findAll();
        return $this->render('jobs/jobs.html.twig', [
            'jobs' => $jobs,
            'categories' => $categories

        ]);
    }
    #[Route('/détails/{id}', name: 'détails')]
    public function details(Job $job): Response
    {
        return $this->render('jobs/détails.html.twig', [
            'job' => $job

        ]);
    }
}

templates/jobs/détails.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail {% endblock %}

{% block body %}
<section id="détails">
    <div class="container-fluid ">
        <div class="col-sm-12 py-5 ">
            <h1 class="text-center ">{{ job.name }}</h1>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row col-sm-12 ">
            <div class="col-md-5 px-5 py-3">
                <img src="{{ asset('img/job/' ~ job.image) }}" alt="" class="img-fluid">
            </div>
            <div class="col-md-7">
                <h4>Description</h4>
                <p class="full-description">{{ job.fullDescription }}</p>
                <h4>Informations</h4>
                <p class="info">
                    Mise en ligne: {{ job.createdAt|date('d/m/Y') }}<br>
                    Type de contrat: {{ job.category.name }}<br>
                    <a href="{{ path('contact') }}" class="btn btn-secondary btn-sm m-3" data-toggle="tooltip" data-placement="bottom"  >Postuler</a>
                </p>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/jobs/jobs.html.twig
{% extends 'base.html.twig' %}

{% block title %}Jobs {% endblock %}

{% block body %}
<section id="jobs">
    <div class="container-fluid ">
        <div class="col-sm-12 ">
            <h1 class="text-center ">Jobs</h1>
        </div>
    </div>
    <div class=" row col-sm-12  " style="overflow: hidden;">
    <!--Cards-->
            {% for job in jobs %}
            <div class=" col-sm-12  col-md-4 py-5" data-category= "{{ job.category.id }}" data-sort = "value">
                <div class="card  m-3" style="min-height: 480px !important;">
                    <img src="{{ asset('img/job/' ~ job.image) }}" class="card-img-top card-img" alt="...">
                    <div class="card-body">
                        <h4 class="card-title">{{ job.name |capitalize }}</h4>
                        <h5 class="card-subtitle text-muted my-3">{{ job.category.name }}</h5>
                        <p class="card-text">{{ job.smallDescription }}</p>
                        <a class="btn btn-outline-secondary" href="{{ path('détails', {id: job.id}) }}" role="button">En savoir plus</a>
                    </div>
                </div>
            </div>
            {% endfor %}
    </div>
</section>

{% endblock %}